#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int die = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int good = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int heart = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ill = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int unknow = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int btnAutoAnalyse = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int btnLogin = 2131099667;
			
			// aapt resource value: 0x7f060004
			public const int btnSave = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int edtAccount = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int edtPassword = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int edtWebServerUrl = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int imgStudy = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int imgWave = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int linearAccout = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int linearPassword = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int linearRole = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int linearWebServerUrl = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int lsvStudy = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int lsvStudyInfo = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int relativeLayout1 = 2131099668;
			
			// aapt resource value: 0x7f06000c
			public const int spinnerRole = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int spnDiagnose = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int swipeRefreshLayout = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int txtRole = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int txvAccount = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int txvPassword = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int txvStudyDetail = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int txvStudyTitle = 2131099670;
			
			// aapt resource value: 0x7f060008
			public const int txvWebServerUrl = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int DiagnoseDetail = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int DiagnoseList = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int StudyDetail = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int StudyItem = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
