version: '3'

services:

  ecgweb-service:
    container_name: ecgwebservice
    image: ecgwebimage
    ports:
      - "6000:6000"
    build:
      context: ./ecgweb
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Shanghai
    volumes:
      - /home/data:/app/data
    restart: always

  nginx-proxy:
    container_name: nginxproxy
    image: nginx    
    ports:
      - "9000:9000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - ecgweb-service
